// Hämta alla blog routes automatiskt
export const blogSlugs = [
  "oka-hemsidans-hastighet",
  "lokal-seo-smaforetag",
  "react-vs-wordpress",
  "framtidsakra-foretag-react-malardalen",
  "lokal-sokmotoroptimering-vastmanland-2026",
  "digital-tillvaxt-smaforetag-malardalen",
  "dominera-google-enkoping",
  "webbutveckling-enkoping-partner",
  "komplett-guide-digital-narvaro-malardalen",
  "webbutveckling-eskilstuna-guide",
  "moderna-hemsidor-vastmanland",
  "seo-strategi-eskilstuna",
  "lokal-seo-tips-vastmanland",
  "frisor-koping-dominera-google",
  "digital-marknadsforing-cafeer",
  "webbdesign-advokatbyraer-vasteras",
  "bokningssystem-frisorer-vastmanland",
  "e-handel-butiker-sala",
  "restauranghemsida-online-meny-sala",
  "seo-byggforetag-malardalen",
  "hemsida-hantverkare-vasteras",
  "byggfirma-vasteras-fler-kunder",
  "restaurang-sala-snabb-hemsida",
  "hastighetsoptimering-foretag-sala",
  "wordpress-vs-react-vasteras",
  "oka-hemsidans-hastighet-koping",
  "hur-lang-tid-bygga-hemsida-vasteras",
  "pris-professionell-hemsida-2026",
  "minska-bounce-rate-vasteras",
  "core-web-vitals-vastmanland",
  "react-vs-wordpress-koping",
  "billig-vs-professionell-hemsida",
  "vad-kostar-hemsida-smaforetag-sala",
  "resan-till-100-pagespeed",
  "framtidssakra-din-digitala-narvaro-i-vastmanland",
  "effektiv-webbutveckling-ai-verktyg-vastmanland",
  "digital-synlighet-vastmanland-seo-ai",
  "framtidssakra-foretag-vastmanland-2026",
];

export const blogRoutes = blogSlugs.map((slug) => ({
  path: `/blogg/${slug}`,
  changefreq: "monthly",
  priority: "0.7",
}));